services:

  postgres:
    image: postgres:17

    container_name: portfolio-postgres

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - portfolio-private


  redis:
    image: redis:8-alpine

    container_name: portfolio-redis

    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    networks:
      - portfolio-private


  pgadmin:
    image: dpage/pgadmin4

    container_name: portfolio-pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - portfolio-private
      - portfolio-public


  backend:
    build:
      context: ./backend

    container_name: portfolio-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis

    networks:
      - portfolio-private
      - portfolio-public


  frontend:
    build:
      context: ./frontend

    container_name: portfolio-frontend

    restart: unless-stopped

    networks:
      - portfolio-public



volumes:

  postgres_data:
  redis_data:
  pgadmin_data:


networks:

  portfolio-public:
    external: true

  portfolio-private:
    external: true